version: "3.9"
services:
  frontend:
    container_name: jbook-app
    image: jbook-app:1.0
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    image: cypress:1.0
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json